# Project-specific file assigning the project module path to the "project" isort section
# The position of the project section is specified below
extend = ".project-import-section.toml"

src = ["src"]

[lint]
select = [
    "B",  # flake8-bugbear
    "E",  # pycodestyle
    "F",  # Pyflakes
    "I",  # isort
    "SIM",  # flake8-simplify
    "UP",  # pyupgrade
]

[lint.isort]
known-first-party = ["org"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "project",
    "local-folder",
]

# Ignore unused imports in __init__.py files (would need __all__ otherwise)
[per-file-ignores]
"__init__.py" = ["F401"]
